language: python
python: 2.7

env:
  - TOXENV=py27-dj111-sqlite
  - TOXENV=py27-dj111-postgres
  - TOXENV=py27-dj111-mysql
  - TOXENV=py34-dj111-postgres
  - TOXENV=py35-dj111-sqlite
  - TOXENV=py35-dj111-postgres
  - TOXENV=py35-dj111-mysql
  - TOXENV=py35-dj20-postgres
  - TOXENV=py35-dj20-mysql
  - TOXENV=py36-dj111-postgres
  - TOXENV=py36-dj20-sqlite
  - TOXENV=py36-dj20-postgres
  - TOXENV=py36-dj20-mysql
  global:
    - PYTHONWARNINGS="default,ignore::PendingDeprecationWarning,ignore::ResourceWarning"

sudo: false

addons:
  postgresql: '9.3'
  mysql: '5.5'
  apt:
    packages:
      - ldap-utils
      - postfix
      - slapd

cache: pip

services:
  - postgres
  - mysql

before_install:
  - pip install codecov

install:
  - pip install tox

before_script:
  - mkdir /tmp/slapd
  - slapd -f test_data/slapd.conf -h ldap://localhost:3389 &
  - sleep 3
  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f test_data/base.ldif

script:
  - tox -e $TOXENV

after_success:
  - codecov

before_deploy:
  - cd ../modoboa
  - django-admin compilemessages
  - cd ..

deploy:
  provider: pypi
  user: tonio
  password:
    secure: SKFrH4cri56YQziqMZ4uvbh5Vto9YrQuBlYRnO9BwcjXbcp6jMpZ+9j+aytMdvcN+xG5of6DmgSIiZsLCOl4LDoPn2oPwWMzZA9T8knSVYt9v1uiBTwDmssIt9QH3wD/o3edpTsSoKw+O2cTT2GaE75+3aTK01+CX4ZsUtkGbTk=
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: '3.6'
    condition: "$DB = POSTGRESQL"
